name: fix_dart
description: Dart Fix Protocol 4.4 Client Library
version: 0.0.1+5
homepage: https://github.com/putraxor/fix_dart

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
